services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_PASSWORD=secret # Root Password for MysQL
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=no
      - MARIADB_DATABASE=studentdb
      - MARIADB_USER=student
      - MARIADB_PASSWORD=student123
    ports:
      - "3136:3306"
    networks:
      - mariadb
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MARIADB_ROOT_PASSWORD=secret
    ports:
      - "8081:80"
    networks:
      - mariadb
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  mariadb:
    name: mariadb